KAFKA_SERVER= 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
KAFKA_API_KEY='XXXXXXXXXXXXXXXXXXXXXXXXXX'
KAFKA_API_SECRET ='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
KAFKA_TOPIC = "transactions"   
KAFKA_TARGET_TOPIC='fraud_transactions'

# PostgreSQL Database Configuration
DB_HOST = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
DB_NAME = "transactions_DB"
DB_USER = "XXXXXXXXXXXXXXX"
DB_PASS = "XXXXXXXXXXXXXX"
DB_PORT = "5432"
